<style type="text/css">
<!--
.style2 {font-size: 36px; }
-->
</style>
<table width="99%" height="102" border="0" cellpadding="0" cellspacing="10">
  <tr>
    <th width="33%" height="82" bgcolor="#0000CC" scope="col"><div align="center" class="style2"><a href="halaman_user.php">Beranda</a></div></th>
    <th width="33%" bgcolor="#FFFF33" scope="col"><div align="center" class="style2"><a href="layanan.php">Layanan</a></div></th>
    <th width="34%" bordercolor="#FFFFFF" bgcolor="#00CC33" scope="col"><div align="center" class="style2"><a href="pesanansaya.php">Pesanan saya</a></div></th>
  </tr>
</table>
<form name="form1" method="post" action="simpanprofil.php">
  <p align="center">TAMPIL DATA PROFILE</p>
  <div align="center">
    <table width="400" border="0" cellpadding="0" cellspacing="8">
      <tr>
        <td width="32">&nbsp;</td>
        <td width="344"><div align="center">Input Data Profile</div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><blockquote>
            <p>Nama</p>
        </blockquote></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><label>
          <input type="text" name="txtnama" id="txtnama" />
        </label></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><blockquote>
            <p>Alamat</p>
        </blockquote></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><label>
          <input type="text" name="txtalamat" id="txtalamat" />
        </label></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><blockquote>
            <p>No hp</p>
        </blockquote></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><label>
          <input type="text" name="txtnohp" id="txtnohp" />
        </label></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><blockquote>
            <p>Jenis Kelamin</p>
        </blockquote></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><label>
          <select name="txtjk" id="txtjk">
            <option>laki-laki</option>
            <option>perempuan</option>
          </select>
        </label></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><label>
          <input type="submit" name="button" id="button" value="simpan" />
          <input type="submit" name="button2" id="button2" value="batal" />
        </label></td>
      </tr>
    </table>
  </div>
</form>
<p align="center">&nbsp;</p>

<p>&nbsp;</p>
